### ISSUE TITLE
Antioch Antioch shows for logo issue for another customer

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/Antioch-Theme#11]
Anthony you created a band-aid for this fix for another customer in this issue #9 

I have another customer with the exact issue. Can you band-aid this again or is this something I can do?

Here's the site:
kentuckytown.com
the login:
kychurch@gmail.com

password
3974mA&jls

**Comment by garand** [comment]
Fixed. They had malicious code in their `functions.php` file.
