### ISSUE TITLE
Is there a responsive view?

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/Antioch-Theme#4]
Ok, not sure if this is an issue but I need help determining what is wrong.  I looked at this site: http://saintbartholomews.org/ on my phone and it is not responsive seems to be that the question is why the logo is small on mobile. Here's the details:
Version of Antioch is the latest (v 1.3.3). The problem is the logo shrinking when "Yes" is selected for Responsive CSS as shown below.

![screen shot 2014-08-12 at 6 12 28 pm](https://cloud.githubusercontent.com/assets/7047954/3898576/ca303834-226d-11e4-9ce4-02457e1798fd.png)

"I purchased and installed Antioch last December and have never been able to get the Responsive CSS to work so that our members could view the website on their iPhones and/or tablets without the logo at the top of the screen shrinking. I clicked the enable "responsive CSS" on Theme Options."

**Comment by angela-crist** [comment]
I'm not sure what the responsive view is suppose to be for these themes.  

It appears that the responsive view was in beta:  "Automatically adapt this site for any device. This feature is currently in beta testing and is turned off by default unless explicitly turned on with this setting."

Perhaps this just means the toggle here Appearance > Theme Options > Responsive CSS

I do not see a difference between on and off:

![slack 20for 20ios 20upload](https://cloud.githubusercontent.com/assets/7047954/3910788/102cfcf2-231b-11e4-8120-593c70a14473.png)

@chriswallace Is this what they are suppose to look like?

**Comment by angela-crist** [comment]
@avclark Can you help me with this?  I need to know if there is a responsive view with the theme or not.  It appears that responsive was in beta... @chriswallace Any thoughts?

**Comment by avclark** [comment]
It is not responsive.  

## 

Adam Clark
Web: avclark.com (http://avclark.com/)
Twitter: @avclark (http://twitter.com/avclark)
Phone: 423-994-0216

**Comment by angela-crist** [comment]
Thanks @avclark for the quick response!  I will let the customer know and have her keep an eye our for our new themes.

**Comment by angela-crist** [comment]
I'm getting more customers ask about the themes being responsive.  I know that above you said they are not responsive and that made sense.  But a customer just brought to my attention that the $49 and $99 version on the site said they are responsive.  Should we take 'responsive' off of the pricing features list (below) and alert the customers that are asking or make it responsive.  Let me know your thoughts @chriswallace @avclark .  ![screen shot 2014-09-09 at 10 14 41 am](https://cloud.githubusercontent.com/assets/7047954/4202869/ae5b6af6-382b-11e4-8e8a-91f3f31fb6eb.png)

**Comment by avclark** [comment]
We are removing those themes by tomorrow at the latest.

**Comment by angela-crist** [comment]
Very nice!  That's exciting.  Are we publishing a blog post and sending an email to tell the customers.  For some reason, they love those themes and I will need something to lean on to provide them when they ask where they went.  

Also, what should I tell those customers that currently have these themes and see that the current site says responsive but they are not.  Please advise.  Thank you, thank you!

**Comment by avclark** [comment]
Chris, may need to weigh in, but as far as I know these themes are not responsive. I've tested them out and unless I'm missing something, they're not. Maybe Frankie was in the middle of implementing something like that and never got around to it? I'm not sure. 

Regarding what to tell customers when the themes come downs, I'll need to get with Chris and/or Brad on that as well. That was the decision we made. People who have support on the old themes will continue to get it, but we won't be selling them anymore.

**Comment by chriswallace** [comment]
The paid themes are responsive. There is a switch in the admin to turn
responsive CSS on or off.

On Tue, Sep 9, 2014 at 9:39 AM, Adam Clark notifications@github.com wrote:

> Chris, may need to weigh in, but as far as I know these themes are not
> responsive. I've tested them out and unless I'm missing something, they're
> not. Maybe Frankie was in the middle of implementing something like that
> and never got around to it? I'm not sure.
> 
> Regarding what to tell customers when the themes come downs, I'll need to
> get with Chris and/or Brad on that as well. That was the decision we made.
> People who have support on the old themes will continue to get it, but we
> won't be selling them anymore.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UpThemes/Antioch-Theme/issues/4#issuecomment-54978846
> .

## 

Chris Wallace
Principal Creative // Lift

mobile 314-406-9109
skype chriswallace7
email/gtalk chris@liftux.com

http://liftux.com

**Comment by avclark** [comment]
Where is that switch?

## 

Adam Clark
Web: avclark.com (http://avclark.com/)
Twitter: @avclark (http://twitter.com/avclark)
Phone: 423-994-0216

**Comment by avclark** [comment]
I'm not finding it on our demo site.

**Comment by avclark** [comment]
Found it.

**Comment by avclark** [comment]
@angela-crist Ok, disregard what I said. I turned on responsive on our Antioch demo and it does work.

**Comment by angela-crist** [comment]
I see the same view whether it is on responsive mode or off.  I went to Appearance -> Theme Options. Am I missing something?  It looked the same for Trinity and Antioch:
![slack_for_ios_upload_360](https://cloud.githubusercontent.com/assets/7047954/4203757/b689fade-3831-11e4-9d17-ba8a0a2996d1.png)
