### ISSUE TITLE
Numerous logo sizes and the theme keeps it small

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/Antioch-Theme#5]
Not sure if this is an issue either but need help in determining what is going on.

Customer issue:
"I am trying to upload a header image in PNG format as recommended. I am also setting the width and height to various pixels but the system seems to ignore it. Here are sets that I have tried but everything gets minimized. The development site is at http://bleupelikan.com/twinoaks/

Sizes:
900x120
570x160
392x110 (this seems to be about as big as it goes)

The problem is that this church's logo somewhat blends into the background. So, the other issue is how do I change the color of the header area? Also, the background color does not change.

I have cleared the cache, tried it in 2 browsers, refreshed the browser, closed the browser and restarted. All things that should take care of it. Nothing changes."

**Comment by matthewsimo** [comment]
Have them make sure "Full Size" is selected while uploading their custom image..

Example:
![image](https://cloud.githubusercontent.com/assets/207644/3909953/50fe5af8-2313-11e4-94e7-f61e071193ae.png)

**Comment by angela-crist** [comment]
Thanks @matthewsimo!  That should take care of him there.  I apologize on the simplicity of that issue. I didn't think to look there. 

The other part was that I was unable to change the main color by going to Appearance > Theme Options > Main Color 
Should I create another issue for that?

**Comment by angela-crist** [comment]
@matthewsimo I tested what you suggested with the image and it shows the full size within the admin but on the site, it stays to the default size.  It is possible that you can't go bigger than the default size?

**Comment by matthewsimo** [comment]
RE: Image size, I was able to add a 900px wide, 120px high image locally without issue. It didn't look awesome because I think the theme wasn't really built to be that flexible..

RE: Main color, as far as I can tell that's the color used in anchor tags and other minor css. Also, there doesn't seem to be any settings available to change the header background image or widget title background images (which create the main color scheme). Which seems sort of silly since the main color is kind of pointless in that case.

Let me know if you have any other questions.

**Comment by angela-crist** [comment]
@chriswallace Do we need to figure out how to create the ability to change the main color within Appearance > Theme Options?  See above conclusion.

**Comment by issuepressapp** [comment]
We're not investing time into enhancements on these old themes. If you
think that's the only way to "fix" it, then I guess we should plan it out.

On Wednesday, August 13, 2014, Angela Crist notifications@github.com
wrote:

> @chriswallace https://github.com/chriswallace Do we need to figure out
> how to create the ability to change the main color within Appearance >
> Theme Options? See above conclusion.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UpThemes/Antioch-Theme/issues/5#issuecomment-52097470
> .

## 

Chris Wallace
Principal Creative // Lift

mobile 314-406-9109
skype chriswallace7
email/gtalk chris@liftux.com

http://liftux.com

**Comment by angela-crist** [comment]
Need help with this one, this customer is still in HelpScout we need a solution to provide or an update.  I have moved the assignment to @avclark since I will be out.
