### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/Antioch-Theme#8]
This customer is trying to install Antioch and it looks like it is uploading and when it gets to 100% it shows this screen attached. Any thoughts on how I should advise him? I tested this on his site and experienced the same issue

![screen shot 2014-09-16 at 3 01 05 pm](https://cloud.githubusercontent.com/assets/7047954/4306866/2e284412-3e84-11e4-891d-2730240780e1.png)

**Comment by chriswallace** [comment]
He's probably trying to install the full zip package which is more than
just the theme. He needs the actual WordPress theme ZIP.

On Wed, Sep 17, 2014 at 11:03 AM, Angela Crist notifications@github.com
wrote:

> Assigned #8 https://github.com/UpThemes/Antioch-Theme/issues/8 to
> @chriswallace https://github.com/chriswallace.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UpThemes/Antioch-Theme/issues/8#event-166714264.

## 

Chris Wallace
Principal Creative // Lift

mobile 314-406-9109
skype chriswallace7
email/gtalk chris@liftux.com

http://liftux.com

**Comment by angela-crist** [comment]
Thanks Chris!
