### ISSUE TITLE
Antioch Antioch shows for logo in Safari 

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/Antioch-Theme#9]
I've tried everything I can think of but I can't figure out why it shows fine in Chrome but not in Safari

![screen shot 2015-01-23 at 3 24 01 pm](https://cloud.githubusercontent.com/assets/7047954/5882036/f65eec62-a313-11e4-9268-041c2fe1f293.png)

Here's the site:
mtolivebaptist.com
Username: david
pw: mtolive

[customer has current support plan]

**Comment by angela-crist** [comment]
I've tried to upload a new image and it still stays the same.  The best I could do was to get it to one Antioch, that happened when I uploaded a new logo in the theme options.  

By the way she has already tried to deactivate plugins and she has the latest version of everything.

**Comment by angela-crist** [comment]
As Anthony noticed: This is what the customer see as well:

I log in, I see the right logo.
I log out, I still see the right logo.
Clear cache, wrong logos again.

**Comment by angela-crist** [comment]
@garand Thanks for creating the band-aid for this.  Do you still need FTP access? To review if there is malicious code here? [see conversation here: https://liftux.slack.com/archives/churchthemes/p1422055479000095]

Host: mtolivebaptist.com
User: mountolive
Pass: Mobc34!

Please provide an update of what is next

**Comment by garand** [comment]
I talked with @chriswallace and he said to just refer them to this site, https://sucuri.net/website-antivirus/malware-removal.

We don't do any server security for customers.
